docker exec -it ballista-rss-ballista-rss-1 alembic revision --autogenerate -m "autogenerated commit"
docker exec -it ballista-rss-ballista-rss-1 alembic upgrade head
echo "Autogenerated migration on $(date)"